In [38]:
from PIL import Image
im = Image.open('../../../ForceInferenceProject/Data/Generated/two_half_spheres.tif')
import numpy as np
imarray = np.array(im)
print(imarray)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [42]:
from skimage import io
im = io.imread('../../../ForceInferenceProject/Data/Generated/two_half_spheres.tif')

In [58]:
im.shape, im.max(), im.dtype
# shape: (z,y,x)

((400, 400, 400), 2, dtype('uint8'))

In [57]:
import matplotlib.pyplot as plt

from ipywidgets import interact

@interact(z=(0, im.shape[0]-1, 1),
          cmap=['viridis','jet','gray'])
def make_plot(z=im.shape[0]//2, cmap='gray'):
    plt.figure(figsize=(5,5))
    plt.imshow(im[z,:,:], cmap=cmap)
    plt.show()

interactive(children=(IntSlider(value=200, description='z', max=399), Dropdown(description='cmap', index=2, op…

In [60]:
im + 100

array([[[100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        ...,
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100]],

       [[100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        ...,
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100]],

       [[100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        ...,
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100]],

       ...,

       [[100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100],
        [100, 100, 100, ..., 100, 100, 100

In [61]:
for z in range(im.shape[0]):
    for y in range(im.shape[1]):
        for x in range(im.shape[2]):
            im[z,y,x] + 100
im

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 

In [36]:
def compareAroundList(array,index1,index2):
    tempList = []
    for w in range(index1-1,index1+2):
        for q in range(index2-1,index2+2):
            tempList.append(array[index1][index2])
    return tempList

def findTE(array):
    tepoints = []
    for y in range(1,len(array)-1):
        for x in range(1, len(array[y])-1):
            tempList = compareAroundList(array,y,x)
            if(len(set(tempList))>3):
                listy = [y,x]
                tepoints.append(listy)
    return tepoints



In [37]:
print(findTE(imarray))

[]


In [30]:
ls ../../../ForceInferenceProject/Data/Generated/two_half_spheres.tif*

Example_Data_Generation.ipynb*      two_intersecting_spheres.tif*
one_sphere.tif*                     two_intersecting_spheres_aniso.tif*
one_sphere_aniso.tif*               two_intersecting_spheres_noise.tif*
one_sphere_noise.tif*               two_touching_spheres.tif*
two_half_spheres.tif*               two_touching_spheres_aniso.tif*
two_half_spheres_aniso.tif*         two_touching_spheres_noise.tif*
two_half_spheres_noise.tif*
